name: moneywhere
description: A new Flutter project.
publish_to: 'none'
version: 1.0.20
environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.3
  formz: ^0.5.0+1
  shared_preferences: ^2.0.20
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  awesome_select: ^6.0.0
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.2.1
  syncfusion_flutter_charts: ^21.1.39
  webview_flutter: ^4.0.7
  flutter_localizations:
    sdk: flutter
  intl: any
  fluwx: ^3.13.0
  sentry_flutter: ^7.5.2
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true

flutter_launcher_icons:
flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/logo.png'